CREATE TABLE COMMENT
(
	ID BIGINT AUTO_INCREMENT,
	PARENT_ID BIGINT NOT NULL,
	TYPE INT NOT NULL,
	COMMENTATOR BIGINT,
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	LIKE_COUNT BIGINT DEFAULT 0,
	COMMENT_COUNT BIGINT DEFAULT 0,
	CONTENT VARCHAR(500),
	CONSTRAINT COMMENT_PK
		PRIMARY KEY (ID)
);